In [4]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
df = pd.read_csv('Porto_Portugal.csv')
df = df.drop(columns=["Unnamed: 0"])

In [24]:
df

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
0,46609,Byron Beach Cabin,208641,Glen,2010-08-21,within an hour,100%,83%,f,1,...,4.92,4.96,5.00,5.00,4.92,4.77,f,1,1,0
1,59459,Tea on the Terrace,285576,Liz,2010-11-12,within an hour,100%,93%,t,1,...,4.93,4.94,4.94,4.94,4.80,4.92,f,1,0,1
2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100%,96%,t,1,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
3,113407,Byron Bay Hinterland House & Pool POCKET PINES,576938,Jo,2011-05-10,within an hour,100%,95%,t,1,...,4.88,4.75,4.96,4.98,4.88,4.71,f,1,1,0
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100%,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6241,1309169243696998503,Tweed Coastal Retreat,8586213,Matthew,2013-09-02,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100%,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6243,1310599322159916197,La Casita Studio,472492532,Camila,2022-07-31,NaN,NaN,NaN,f,2,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84%,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5
6245,1310716580562175377,Bayshore Bungalow No.14,664353848,Naomi,2024-11-28,within an hour,100%,100%,f,12,...,NaN,NaN,NaN,NaN,NaN,NaN,t,12,12,0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6246 entries, 0 to 6245
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            6246 non-null   int64
 1   name                                          6246 non-null   object
 2   host_id                                       6246 non-null   int64
 3   host_name                                     6246 non-null   object
 4   host_since                                    6246 non-null   object
 5   host_response_time                            5523 non-null   object
 6   host_response_rate                            5523 non-null   object
 7   host_acceptance_rate                          5728 non-null   object
 8   host_is_superhost                             6142 non-null   object
 9   host_listings_count                           6246 non-null   int64
 10  host_identity_verified                        6246 non-null   object
 11  neighbourhood_cleansed                        6246 non-null   object
 12  neighbourhood_group_cleansed                  0 non-null      float64
 13  latitude                                      6246 non-null   float64
 14  longitude                                     6246 non-null   float64
 15  property_type                                 6246 non-null   object
 16  room_type                                     6246 non-null   object
 17  accommodates                                  6246 non-null   int64
 18  bathrooms                                     5868 non-null   float64
 19  bathrooms_text                                6246 non-null   object
 20  bedrooms                                      6212 non-null   float64
 21  beds                                          5860 non-null   float64
 22  price                                         5868 non-null   object
 23  minimum_nights                                6246 non-null   int64
 24  maximum_nights                                6246 non-null   int64
 25  minimum_minimum_nights                        6246 non-null   int64
 26  maximum_minimum_nights                        6246 non-null   int64
 27  minimum_maximum_nights                        6246 non-null   int64
 28  maximum_maximum_nights                        6246 non-null   int64
 29  minimum_nights_avg_ntm                        6246 non-null   float64
 30  maximum_nights_avg_ntm                        6246 non-null   float64
 31  has_availability                              6211 non-null   object
 32  availability_30                               6246 non-null   int64
 33  availability_60                               6246 non-null   int64
 34  availability_90                               6246 non-null   int64
 35  availability_365                              6246 non-null   int64
 36  number_of_reviews                             6246 non-null   int64
 37  number_of_reviews_ltm                         6246 non-null   int64
 38  number_of_reviews_l30d                        6246 non-null   int64
 39  review_scores_rating                          5161 non-null   float64
 40  review_scores_accuracy                        5159 non-null   float64
 41  review_scores_cleanliness                     5159 non-null   float64
 42  review_scores_checkin                         5159 non-null   float64
 43  review_scores_communication                   5159 non-null   float64
 44  review_scores_location                        5159 non-null   float64
 45  review_scores_value                           5159 non-null   float64
 46  instant_bookable                              6246 non-null   object
 47  calculated_host_listings_count                6246 non-null   int64
 48  calculated_host_listings_count_entire_homes   6246 non-null   int64
 49  calculated_host_listings_count_private_rooms  6246 non-null   int64
dtypes: float64(15), int64(20), object(15)
memory usage: 2.4+ MB

a) Los registros de los host cuyo “host_response_rate” sea mayor a 95% y que no sean “superhost”

In [28]:
df['host_response_rate']=df['host_response_rate'].str.replace('%','')
df['host_response_rate']=df['host_response_rate'].astype(float)

In [30]:
filtro1 = df[(df['host_response_rate'] >= 95) & (df['host_is_superhost'] == 'f')]
filtro1

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
0,46609,Byron Beach Cabin,208641,Glen,2010-08-21,within an hour,100.0,83%,f,1,...,4.92,4.96,5.00,5.00,4.92,4.77,f,1,1,0
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100.0,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
27,596843,Tranquil Studio 5kms from Byron Bay,2921954,Natasha,2012-07-13,within an hour,100.0,67%,f,1,...,4.89,4.73,4.93,4.92,4.85,4.80,f,1,0,1
30,648394,Byron 4 Star Room! Walk to Beach,791858,Philip,2011-07-07,within a few hours,100.0,63%,f,2,...,4.65,4.57,4.78,4.91,4.65,4.43,f,2,0,2
32,706964,Room w/own entrance kitchenette & bthrm,998147,Emma,2011-08-20,within an hour,100.0,90%,f,1,...,4.73,4.82,4.88,4.89,4.66,4.68,f,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6236,1309067880719688536,Corporate & Family Beach Retreat,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6237,1309069369622464898,Drift South Apartment 1,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6238,1309070359598412122,Luxury Apartment 1220 at Bells Boulevard,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6239,1309070877433877660,Ocean View on Marine Parade - #2,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6245,1310716580562175377,Bayshore Bungalow No.14,664353848,Naomi,2024-11-28,within an hour,100.0,100%,f,12,...,NaN,NaN,NaN,NaN,NaN,NaN,t,12,12,0

In [32]:
filtro1.to_csv("host_response_rate.csv")

b) Los registros cuyas propiedades no tengan “1 baño”

In [40]:
filtro2 = df[(df['bathrooms'] != 1)]
filtro2

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100.0,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
5,340699,A Perfect Stay - Drift,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.62,4.79,4.81,4.75,4.72,4.55,t,98,98,0
7,399928,Byron Bay Beach house,1996249,Frederique,2012-03-23,within an hour,100.0,100%,t,1,...,4.85,4.66,4.98,5.00,4.58,4.58,f,1,1,0
11,550619,Spacious A/C apartment - dead centre of town!,2706340,Elaine,2012-06-21,within an hour,100.0,94%,NaN,10,...,4.89,4.80,4.97,4.93,4.97,4.84,t,9,9,0
12,557918,A Summer Cottage,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.63,4.47,4.94,4.81,4.69,4.44,t,98,98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6237,1309069369622464898,Drift South Apartment 1,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6238,1309070359598412122,Luxury Apartment 1220 at Bells Boulevard,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6240,1309077396237633949,2 Bedroom Rooftop Haven,91928999,Tweed Coast Holidays,2016-08-26,within an hour,100.0,99%,t,25,...,NaN,NaN,NaN,NaN,NaN,NaN,t,24,24,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100.0,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84.0,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5

In [42]:
filtro2.to_csv("bathrooms.csv")

c) Los registros que tengan un precio entre “100 y 200 US” (Realizar conversión de moneda)

In [61]:
df['price']=df['price'].str.replace('$','')
df['price']=df['price'].str.replace(',','')
df['price']=df['price'].astype(float)

In [65]:
#1.05 dólares = 1 euro
filtro3 = df[(df['price'] >= 95.05) & (df['price'] <= 190.1)]
filtro3

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100.0,96%,t,1,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
9,428075,"Agave Escape -gateway to beaches, rainforest, ...",2127754,Estelle,2012-04-12,within an hour,100.0,100%,t,2,...,4.93,4.75,4.88,4.96,4.89,4.84,f,2,2,0
25,587766,Lilli Pilli Guest Room with ensuite,2899669,Jodie,2012-07-11,within an hour,100.0,100%,t,3,...,4.89,4.92,4.97,4.95,4.81,4.85,t,3,1,2
27,596843,Tranquil Studio 5kms from Byron Bay,2921954,Natasha,2012-07-13,within an hour,100.0,67%,f,1,...,4.89,4.73,4.93,4.92,4.85,4.80,f,1,0,1
29,631809,Nature Lover's Vegan Paradise,3142270,Garry,2012-08-02,within an hour,100.0,100%,t,3,...,4.96,4.88,4.97,4.98,4.96,4.96,t,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6200,1307038659250063442,Edan Gardens Restaway,231588972,Neville,2018-12-20,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6213,1307759517597400210,Indigo Sailfish- Flat w/ Shared Pool by uHoliday,62341131,Daniel,2016-03-09,within an hour,100.0,100%,t,77,...,NaN,NaN,NaN,NaN,NaN,NaN,t,73,73,0
6223,1308302175367670914,Coastal Echo - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100.0,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6228,1308452050205746654,Ellerby Farm Tiny House,170855660,Heather,2018-01-30,within an hour,100.0,100%,t,2,...,NaN,NaN,NaN,NaN,NaN,NaN,f,2,2,0
6243,1310599322159916197,La Casita Studio,472492532,Camila,2022-07-31,NaN,NaN,NaN,f,2,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0

In [67]:
filtro3.to_csv("price.csv")

d) Los registros que sean “instant_bookable” y que hallan verificado su perfil “host_identity_verified”

In [70]:
filtro4 = df[(df['instant_bookable'] == 't') & (df['host_identity_verified'] == 't')]
filtro4

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100.0,96%,t,1,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
5,340699,A Perfect Stay - Drift,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.62,4.79,4.81,4.75,4.72,4.55,t,98,98,0
8,410733,Byron Bay Breathing Space - Beachside,2034145,Al,2012-03-29,NaN,NaN,100%,f,1,...,4.80,4.91,4.97,4.92,4.90,4.53,t,1,0,1
10,515349,A Classic Country Cabin,2538287,Justine,2012-06-03,NaN,NaN,100%,t,1,...,4.78,4.52,4.96,4.93,4.86,4.73,t,1,1,0
12,557918,A Summer Cottage,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.63,4.47,4.94,4.81,4.69,4.44,t,98,98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6241,1309169243696998503,Tweed Coastal Retreat,8586213,Matthew,2013-09-02,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100.0,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6243,1310599322159916197,La Casita Studio,472492532,Camila,2022-07-31,NaN,NaN,NaN,f,2,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84.0,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5
6245,1310716580562175377,Bayshore Bungalow No.14,664353848,Naomi,2024-11-28,within an hour,100.0,100%,f,12,...,NaN,NaN,NaN,NaN,NaN,NaN,t,12,12,0

In [72]:
filtro4.to_csv("verified.csv")

e) Los registros de los tipos de cuarto: “hotel room” o “Private room”

In [86]:
filtro5 = df[(df['room_type'] == 'Entire home/apt') | (df['room_type'] == 'Private room')]
filtro5

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
0,46609,Byron Beach Cabin,208641,Glen,2010-08-21,within an hour,100.0,83%,f,1,...,4.92,4.96,5.00,5.00,4.92,4.77,f,1,1,0
1,59459,Tea on the Terrace,285576,Liz,2010-11-12,within an hour,100.0,93%,t,1,...,4.93,4.94,4.94,4.94,4.80,4.92,f,1,0,1
2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100.0,96%,t,1,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
3,113407,Byron Bay Hinterland House & Pool POCKET PINES,576938,Jo,2011-05-10,within an hour,100.0,95%,t,1,...,4.88,4.75,4.96,4.98,4.88,4.71,f,1,1,0
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100.0,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6241,1309169243696998503,Tweed Coastal Retreat,8586213,Matthew,2013-09-02,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100.0,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6243,1310599322159916197,La Casita Studio,472492532,Camila,2022-07-31,NaN,NaN,NaN,f,2,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84.0,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5
6245,1310716580562175377,Bayshore Bungalow No.14,664353848,Naomi,2024-11-28,within an hour,100.0,100%,f,12,...,NaN,NaN,NaN,NaN,NaN,NaN,t,12,12,0

In [88]:
filtro5.to_csv("room_type.csv")

f) Los registros que tengan mas de 4 “accommodates”

In [90]:
filtro6 = df[(df['accommodates'] > 4)]
filtro6

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100.0,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
5,340699,A Perfect Stay - Drift,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.62,4.79,4.81,4.75,4.72,4.55,t,98,98,0
7,399928,Byron Bay Beach house,1996249,Frederique,2012-03-23,within an hour,100.0,100%,t,1,...,4.85,4.66,4.98,5.00,4.58,4.58,f,1,1,0
11,550619,Spacious A/C apartment - dead centre of town!,2706340,Elaine,2012-06-21,within an hour,100.0,94%,NaN,10,...,4.89,4.80,4.97,4.93,4.97,4.84,t,9,9,0
12,557918,A Summer Cottage,1649158,A Perfect Stay,2012-01-24,within a few hours,92.0,100%,f,100,...,4.63,4.47,4.94,4.81,4.69,4.44,t,98,98,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6237,1309069369622464898,Drift South Apartment 1,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6239,1309070877433877660,Ocean View on Marine Parade - #2,192774381,Kingscliff Accommodation,2018-05-31,within an hour,96.0,97%,f,112,...,NaN,NaN,NaN,NaN,NaN,NaN,t,112,109,3
6241,1309169243696998503,Tweed Coastal Retreat,8586213,Matthew,2013-09-02,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100.0,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84.0,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5

In [92]:
filtro6.to_csv("accomodation.csv")